version: "3.9"

services:
  site1:
    image: httpd:2.4
    volumes:
      - ./site1/:/usr/local/apache2/htdocs/
    ports:
      - 8081:80
    restart: always

  site2:
    image: httpd:2.4
    volumes:
      - ./site2/:/usr/local/apache2/htdocs/
    ports:
      - 8082:80
    restart: always