---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: AppCluster
  region: us-east-1
  version: "1.21"
vpc:
  id: "vpc-0da4486de7f8f0fc7"
  subnets:
    public:
      us-east-1a:
        id: "subnet-0c95b029c4010b1d7"
      us-east-1b:
        id: "subnet-0f4e4523e24c62bd2"
    private:
      us-east-1a:
        id: "subnet-0cdf9e7868eb05d9b"
      us-east-1b:
        id: "subnet-0d21cd178c6cbf5c4"
nodeGroups:
  - name: nodegrp-01
    amiFamily: "Ubuntu2004"
    privateNetworking: true
    instancePrefix: eks
    instanceName: instance
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 6
    subnets:
      - subnet-0cdf9e7868eb05d9b
      - subnet-0d21cd178c6cbf5c4
    ssh:
      publicKeyName: eks_key
    securityGroups:
      attachIDs: ['sg-07ce9bb6edda0522f']